### ISSUE TITLE
Cloudinary - to display mimyType and size 

### ISSUE THREAD

**Issue by Ewa-Anna** [Ewa-Anna/Django-Task-Tracker#173]
Cloudinary - to display mimyType and size

**Comment by Ewa-Anna** [comment]
Done, now all endpoints returning url for attachments, also returns mimeType and size in mb:
![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/50e8dbbf-148f-47be-b6e1-fe1b0fcfffea)

**Comment by HurasAdam** [comment]
Currently,  endpoint returns file size in megabytes (MB), causing issues when the file size is less than 1 MB, resulting in a display of 0 MB. To address this and provide clearer data for clients, we propose updating the file size formatting.

Proposed Solution:
Instead of returning the file size in MB, I suggest returning it with precision to kilobytes (KB). This adjustment will prevent display of 0 MB for files smaller than 1 MB and make it easier for clients to interpret the data.

Example:

If the file size is 200 KB, returned value will be 0.2 MB.
